import time
from termcolor import colored
p = print
def boot():
    p("strating sythem boot...")
    time.sleep(0.3)
    p("Analyzing Processor speed...")
    time.sleep(0.3)
    p("Checking memory modules...")
    time.sleep(0.3)
    p("Loading sythem resources... ")
    time.sleep(0.3)
    p("Starting network connection...")
    time.sleep(1.3)
    p("Booting operating sythem...")
    time.sleep(0.3)
    p("Configuring sytheme setting...")
    time.sleep(0.3)
    p("Loading user profiles...")
    time.sleep(1.3)
    p("Mounting files sythems...")
    time.sleep(0.3)
    p("Starting sythem services...")
    time.sleep(0.3)
    p("Lunching user interface...")
    time.sleep(2)
    p("Lunching user interface| 10% |")
    time.sleep(1)
    p("Lunching user interface| 28% |")
    time.sleep(1.3)
    p("Lunching user interface| 35% |")
    time.sleep(0.3)
    p("Lunching user interface| 47% |")
    time.sleep(1)
    p("Lunching user interface| 52% |")
    time.sleep(0.3)
    p("Lunching user interface| 65% |")
    p("Lunching user interface| 78% |")
    time.sleep(1)
    p("Lunching user interface| 84% |")
    time.sleep(1)
    p("Lunching user interface| 97% |")
    p("Lunching user interface| 100%|")
    p(".")
    time.sleep(2)
    p(".")
    time.sleep(1)
    p(".")
    p(colored("Sythem boot complete !", "green"))
    time.sleep(2)


boot()
    
